# NUMPY :-
- NumPy, short for "Numerical Python," is a fundamental package in Python for numerical computations. 
- NumPy introduces the ndarray (N-dimensional array) data structure, which allows you to perform element-wise operations on arrays and matrices efficiently. 
- These operations are often much faster than using traditional Python lists due to NumPy's optimized implementation in C.
- NumPy is a foundational library for many other scientific computing libraries in Python, such as SciPy, scikit-learn, and pandas. 

---
# Numpy Arrays (ndarrays) ⇨
- NumPy arrays are similar to Python lists but come with many advantages that make them essential for numerical and scientific computing.
    - *Homogeneous Data Type.*
    -  *Multidimensional Arrays.*
    - *Memory Efficiency.*
    - *Fast Element-Wise Operations.*
    - *Indexing and Slicing.*
---

#### TO download Numpy Run the following command on your terminal.


``` pip install numpy```

---

In [1]:
# importing numpy
import numpy as np

In [2]:
# np.array
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [ ]:
np.array([[1,2,3],
          [4,5,6]])

In [5]:
b = np.array([[1,2,3],
              [4,3,2]])

In [12]:
b.shape

(3, 3)

In [11]:
b = np.array([[1,2,3],
              [4,5,6],
              [3,4,4]])
print(b)

[[1 2 3]
 [4 5 6]
 [3 4 4]]


In [ ]:
type(b)

In [9]:
c = np.array([[[1,2],
               [3,4]],
             [[5,6],
              [7,8]]])

In [ ]:
c

In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [13]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
c.dtype

dtype('int32')

In [16]:
# dtype
np.array([1,2,3],dtype='float32')

array([1., 2., 3.], dtype=float32)

In [17]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
c=np.arange(1,9).reshape(2,2,2)
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
a = np.arange(1,16).reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [22]:
c=c.reshape(1,-1)

In [24]:
c.ndim

2

In [25]:
c.shape

(1, 8)

In [23]:
c

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [26]:
# np.ones
np.ones((4,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.ones(10,dtype='int32')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
# np.zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
# np.random
np.random.random((4))

array([0.77822312, 0.42382614, 0.53326088, 0.43523021])

In [31]:
np.random.randint(1,11,10).reshape(5,2)

array([[ 9,  2],
       [ 7,  6],
       [ 5,  8],
       [ 1,  4],
       [ 8, 10]])

In [35]:
np.random.randint(1,50,25).reshape(5,5)

array([[11, 23,  2,  9, 22],
       [41, 31,  8, 11, 10],
       [20, 31,  2, 34, 30],
       [28, 47, 41, 13,  4],
       [44, 33, 36, 16, 22]])

In [36]:
# np.linspace
np.linspace(1,100,5,dtype='int32')

array([  1,  25,  50,  75, 100])

In [37]:
# np.identity
np.identity(4,dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Array operations

In [ ]:
a = np.array([[[1,2,3],
               [1,3,5]],
              [[1,4,5],
               [3,5,6]]])

In [ ]:
a

In [38]:
a = np.arange(1,21,dtype='int32').reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [40]:
b = np.array([3,4,5])
b.ndim

1

In [39]:
# ndim
a.ndim

2

In [41]:
# shape
a.shape

(4, 5)

In [42]:
# size
a.size

20

In [43]:
a.dtype

dtype('int32')

In [44]:
# itemsize - function returns the length of one array element in bytes.
a.itemsize

4

In [ ]:
20/5

In [45]:
# astype()
a.astype(np.float16)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]], dtype=float16)

In [46]:
# scalar operations

b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
b *2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [48]:
b **2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [49]:
b ** 0.5

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [50]:
b - 5

array([[-5, -4, -3],
       [-2, -1,  0],
       [ 1,  2,  3]])

In [51]:
b / 2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [52]:
b % 2

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [ ]:
# realtional
b % 2 == 0

In [ ]:
[[3,3,4,4],
 [5,6,7,8]]

In [53]:
# vector operations
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [54]:
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [55]:
# vector operations
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [56]:
a = np.array([[0,2,1],[1,2,4]])
b= np.array([[1,4],[2,5],[3,6]])
print(a)
print(b)

[[0 2 1]
 [1 2 4]]
[[1 4]
 [2 5]
 [3 6]]


In [57]:
# np.dot
np.dot(a,b)

array([[ 7, 16],
       [17, 38]])

In [58]:
a = np.array([1,2,3])
b = np.array([3,4,5])
np.cross(a,b)

array([-2,  4, -2])

In [59]:
# np.cross
np.cross(a,b)

array([-2,  4, -2])

In [60]:
a = np.random.random(4)
a

array([0.81475873, 0.62682181, 0.92298145, 0.34005001])

In [61]:
a.round()

array([1., 1., 1., 0.])

In [62]:
np.round(a*100)

array([81., 63., 92., 34.])

In [63]:
# prod 
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
np.arange(1,5)

array([1, 2, 3, 4])

In [65]:
np.prod(np.arange(1,5))

24

In [66]:
a.prod()

479001600

In [ ]:
# 0 ==> column
# 1 ==> rows

In [67]:
np.prod(a,axis=0)

array([ 45, 120, 231, 384])

In [68]:
np.prod(a,axis=1)

array([   24,  1680, 11880])

In [69]:
# max
np.max(a)

12

In [70]:
# min
np.min(a)


1

In [71]:
# sum
np.sum(a)

78

In [72]:
# stats [mean,median,std,var]
np.mean(a)

6.5

In [75]:
# round/floor/ceil
a = np.random.random(4)
a

array([0.63443548, 0.22862966, 0.02734961, 0.84530248])

In [76]:
np.floor(a)

array([0., 0., 0., 0.])

In [77]:
np.ceil(a)

array([1., 1., 1., 1.])

In [78]:
np.round(a)

array([1., 0., 0., 1.])

In [ ]:
# reshape/Transpose/ravel

In [79]:
a = np.random.randint(1,51,20).reshape(4,5)
a

array([[17, 48,  1, 32, 47],
       [39, 34, 27, 14, 12],
       [20, 45, 17, 18,  4],
       [15, 14, 38, 12, 44]])

In [80]:
np.transpose(a)
a.T

array([[17, 39, 20, 15],
       [48, 34, 45, 14],
       [ 1, 27, 17, 38],
       [32, 14, 18, 12],
       [47, 12,  4, 44]])

In [81]:
np.ravel(a)

array([17, 48,  1, 32, 47, 39, 34, 27, 14, 12, 20, 45, 17, 18,  4, 15, 14,
       38, 12, 44])

In [82]:
# stacking hstack, vstack
a = np.arange(1,10).reshape(3,3)
b = np.arange(9,18).reshape(3,3)
print(a,b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [83]:
c = np.hstack((a,b))
c

array([[ 1,  2,  3,  9, 10, 11],
       [ 4,  5,  6, 12, 13, 14],
       [ 7,  8,  9, 15, 16, 17]])

In [84]:
d = np.vstack((a,b))
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [85]:
# splitting 
# hsplit [splits colums],
# vsplit [splits rows]

np.hsplit(c,2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [86]:
np.vsplit(d,2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [87]:
a= np.arange(1,25).reshape(6,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [88]:
for i in a:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[17 18 19 20]
[21 22 23 24]


In [89]:
# nditer
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [90]:
# indexing and slicing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [91]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
a2[0,1:3]

array([1, 2])

In [ ]:
a2[::2,1::2]

In [ ]:
rows = 0,2
columns = 1,3

In [ ]:
a2[:,::2]

In [ ]:
a2[:,2]

In [ ]:
a2[1:,-2:]

In [ ]:
a2[0,:]

In [ ]:
a2[0:2,0:2]

In [ ]:
a2[:,0::2]

In [ ]:
a2[0::2,1]

In [ ]:
a2[0:2,1::2]

In [ ]:
a2

In [ ]:
a2[0::2,1::2]

In [ ]:
a3

In [ ]:
a3[-1]

In [ ]:
a3[:,0,1]

In [ ]:
a3[1]

In [ ]:
a3[1,:,0]

In [ ]:
a3[0,0,1]

In [ ]:
a3[0,0,0]

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

In [ ]:
a3[::2,::2,0]

In [ ]:
a3[::2,-1,-1]

In [ ]:
a3[::2,1:,1:]

In [ ]:
a3[0,::2,::2]

In [ ]:
a3[:,0,0]

In [ ]:
a3[:,2,2]

In [ ]:
a3[1::2,1,1]

In [ ]:
a = np.arange(24).reshape(6,4)
a

In [ ]:
a[[0,5],::3]

In [ ]:
a[[0,2],::2]

In [ ]:
a[[1,2],[0]]

In [ ]:
a[1:3,1:3]

In [99]:
a= np.random.randint(1,100,50).reshape(5,10)
a

array([[36, 41, 57, 65, 59, 31, 15, 80,  2, 58],
       [37, 24, 42, 39, 30, 79, 68, 67, 21, 33],
       [ 6, 25,  8, 17, 82, 84, 37, 73, 73, 85],
       [39, 13,  1,  8, 79, 32, 14, 27, 95, 46],
       [67, 13, 61, 49,  6, 27, 27, 66, 26, 31]])

In [103]:
a[a>80]

array([82, 84, 85, 95])

In [104]:
a[a %2 ==0]

array([36, 80,  2, 58, 24, 42, 30, 68,  6,  8, 82, 84,  8, 32, 14, 46,  6,
       66, 26])

In [105]:
a[a %2 !=0]

array([41, 57, 65, 59, 31, 15, 37, 39, 79, 67, 21, 33, 25, 17, 37, 73, 73,
       85, 39, 13,  1, 79, 27, 95, 67, 13, 61, 49, 27, 27, 31])

In [106]:
a[a > 80]

array([82, 84, 85, 95])

In [108]:
a[~(a>80) & (a %2 ==0)]

array([36, 80,  2, 58, 24, 42, 30, 68,  6,  8,  8, 32, 14, 46,  6, 66, 26])

In [109]:
# boolean indexing
a[~(a > 80) & ~(a %2 !=0)]

array([36, 80,  2, 58, 24, 42, 30, 68,  6,  8,  8, 32, 14, 46,  6, 66, 26])

In [ ]:
# & ==> for adding multiple conditons
# ~ ==> represents !=

In [ ]:

a[(a > 20) & (a % 2 != 0)]

In [ ]:
a[~(a%4 ==0)]

In [110]:
# null
a = np.array([1,2,3,np.nan])

In [111]:
a

array([ 1.,  2.,  3., nan])