# NUMPY :-
- NumPy, short for "Numerical Python," is a fundamental package in Python for numerical computations. 
- NumPy introduces the ndarray (N-dimensional array) data structure, which allows you to perform element-wise operations on arrays and matrices efficiently. 
- These operations are often much faster than using traditional Python lists due to NumPy's optimized implementation in C.
- NumPy is a foundational library for many other scientific computing libraries in Python, such as SciPy, scikit-learn, and pandas. 

---
# Numpy Arrays (ndarrays) ⇨
- NumPy arrays are similar to Python lists but come with many advantages that make them essential for numerical and scientific computing.
    - *Homogeneous Data Type.*
    -  *Multidimensional Arrays.*
    - *Memory Efficiency.*
    - *Fast Element-Wise Operations.*
    - *Indexing and Slicing.*
---

#### TO download Numpy Run the following command on your terminal.


``` pip install numpy```

---

In [1]:
# importing numpy
import numpy as np

In [2]:
# np.array
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [5]:
b = np.array([[1,2,3],
              [4,3,2]])

In [6]:
b

array([[1, 2, 3],
       [4, 3, 2]])

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

In [ ]:
type(b)

In [7]:
c = np.array([[[1,2],
               [3,4]],
             [[5,6],
              [7,8]]])

In [8]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [9]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
c.dtype

dtype('int32')

In [12]:
2**31

2147483648

In [ ]:
2**15

In [ ]:
2**8

In [ ]:
2**7

In [13]:
# dtype
np.array([1,2,3],dtype='float16')

array([1., 2., 3.], dtype=float16)

In [14]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
c=np.arange(1,9).reshape(2,2,2)
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
a = np.arange(1,16).reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [19]:
c=c.reshape(1,-1)

In [20]:
c.ndim

2

In [21]:
c

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [24]:
# np.ones
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.ones(10,dtype='int32')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
# np.zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
# np.random
np.random.random((4))

array([0.23063899, 0.11697002, 0.60440865, 0.61451893])

In [29]:
np.random.randint(1,50,25).reshape(5,5)

array([[ 4, 16, 37, 47, 41],
       [27, 24, 17, 34, 47],
       [37,  8, 23, 14, 42],
       [10,  5, 27, 10, 19],
       [ 8, 16, 49, 24, 31]])

In [31]:
# np.linspace
np.linspace(1,100,5,dtype='int32')

array([  1,  25,  50,  75, 100])

In [33]:
# np.identity
np.identity(4,dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Array operations

In [36]:
a = np.array([[[1,2,3],
               [1,3,5]],
              [[1,4,5],
               [3,5,6]]])

In [37]:
a

array([[[1, 2, 3],
        [1, 3, 5]],

       [[1, 4, 5],
        [3, 5, 6]]])

In [55]:
a = np.arange(1,21,dtype='int32').reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [56]:
# ndim
a.ndim

2

In [57]:
# shape
a.shape

(4, 5)

In [58]:
# size
a.size

20

In [61]:
a.dtype

dtype('int32')

In [62]:
# itemsize - function returns the length of one array element in bytes.
a.itemsize

4

In [63]:
20/5

4.0

In [64]:
# astype()
a.astype(np.float16)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]], dtype=float16)

In [65]:
# scalar operations

b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
b *2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [67]:
b **2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [68]:
b ** 0.5

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [69]:
b - 5

array([[-5, -4, -3],
       [-2, -1,  0],
       [ 1,  2,  3]])

In [70]:
b / 2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [72]:
b % 2

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [73]:
# realtional
b % 2 == 0

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [74]:
# vector operations
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [75]:
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [76]:
# vector operations
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [79]:
a = np.array([[0,2,1],[1,2,4]])
b= np.array([[1,4],[2,5],[3,6]])
print(a)
print(b)

[[0 2 1]
 [1 2 4]]
[[1 4]
 [2 5]
 [3 6]]


In [80]:
# np.dot
np.dot(a,b)

array([[ 7, 16],
       [17, 38]])

In [81]:
# np.cross
np.cross(a,b)

ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2,) and arg 1 with shape (3,).

In [82]:
a = np.array([1,2,3])
b = np.array([3,4,5])
np.cross(a,b)

array([-2,  4, -2])

In [86]:
a = np.random.random(4)
a

array([0.47904017, 0.80905446, 0.14833187, 0.00240349])

In [88]:
a.round()

array([0., 1., 0., 0.])

In [89]:
np.round(a*100)

array([48., 81., 15.,  0.])

In [90]:
# prod 
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
np.arange(1,5)

array([1, 2, 3, 4])

In [91]:
np.prod(np.arange(1,5))

24

In [93]:
a.prod()

479001600

In [ ]:
# 0 ==> column
# 1 ==> rows

In [95]:
np.prod(a,axis=0)

array([ 45, 120, 231, 384])

In [94]:
np.prod(a,axis=1)

array([   24,  1680, 11880])

In [96]:
# max
np.max(a)

12

In [ ]:
# min

In [ ]:
# sum

In [97]:
# stats [mean,median,std,var]
np.mean(a)

6.5

In [100]:
# round/floor/ceil
a = np.random.random(4)
a

array([0.25188883, 0.56126662, 0.83101408, 0.25873603])

In [101]:
np.floor(a)

array([0., 0., 0., 0.])

In [102]:
np.ceil(a)

array([1., 1., 1., 1.])

In [ ]:
# reshape/Transpose/ravel

In [106]:
a = np.random.randint(1,51,20).reshape(4,5)
a

array([[50,  8, 37, 43, 19],
       [29, 25, 38, 47, 13],
       [17, 24, 31, 28,  3],
       [38, 11, 45, 35, 47]])

In [108]:
np.transpose(a)
a.T

array([[50, 29, 17, 38],
       [ 8, 25, 24, 11],
       [37, 38, 31, 45],
       [43, 47, 28, 35],
       [19, 13,  3, 47]])

In [109]:
np.ravel(a)

array([50,  8, 37, 43, 19, 29, 25, 38, 47, 13, 17, 24, 31, 28,  3, 38, 11,
       45, 35, 47])

In [111]:
# stacking hstack, vstack
a = np.arange(1,10).reshape(3,3)
b = np.arange(9,18).reshape(3,3)
print(a,b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [115]:
c = np.hstack((a,b))
c

array([[ 1,  2,  3,  9, 10, 11],
       [ 4,  5,  6, 12, 13, 14],
       [ 7,  8,  9, 15, 16, 17]])

In [123]:
d = np.vstack((a,b))
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [125]:
# splitting 
# hsplit [splits colums],
# vsplit [splits rows]

np.hsplit(c,2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [129]:
np.vsplit(d,6)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[ 9, 10, 11]]),
 array([[12, 13, 14]]),
 array([[15, 16, 17]])]

In [130]:
a= np.arange(1,25).reshape(6,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [131]:
for i in a:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[17 18 19 20]
[21 22 23 24]


In [133]:
# nditer
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [134]:
# indexing and slicing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [135]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
rows = 0,2
columns = 1,3

In [147]:
a2[:,0::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [140]:
a2[0,1:3]

array([1, 2])

In [141]:
a2[:,2]

array([ 2,  6, 10])

In [144]:
a2[1:,-2:]

array([[ 6,  7],
       [10, 11]])

In [149]:
a2[0,:]

array([0, 1, 2, 3])

In [150]:
a2[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [ ]:
a2[:,0::2]

In [ ]:
a2[0::2,1]

In [ ]:
a2[0:2,1::2]

In [ ]:
a2

In [ ]:
a2[0::2,1::2]

In [151]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [156]:
a3[:,0,1]

array([1, 5])

In [153]:
a3[1]

array([[4, 5],
       [6, 7]])

In [157]:
a3[1,:,0]

array([4, 6])

In [ ]:
a3[0,0,1]

In [159]:
a3[0,0,0]

0

In [160]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [168]:
a3[::2,::2,0]

array([[ 0,  6],
       [18, 24]])

In [165]:
a3[::2,-1,-1]

array([ 8, 26])

In [163]:
a3[::2,1:,1:]

array([[[ 4,  5],
        [ 7,  8]],

       [[22, 23],
        [25, 26]]])

In [ ]:
a3[0,::2,::2]

In [ ]:
a3[:,0,0]

In [ ]:
a3[:,2,2]

In [ ]:
a3[1::2,1,1]

In [169]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [179]:
a[[0,5],::3]

array([[ 0,  3],
       [20, 23]])

In [174]:
a[[0,2],::2]

array([[ 0,  2],
       [ 8, 10]])

In [ ]:
a[[1,2],[0]]

In [ ]:
a[1:3,1:3]

In [180]:
a= np.random.randint(1,100,50).reshape(5,10)
a

array([[87, 67, 39, 34, 70, 36, 73, 60,  7, 84],
       [58, 76, 35, 80, 62, 96,  5, 13, 80, 20],
       [74, 62,  6, 70, 83, 40, 26, 19, 50, 53],
       [16, 57,  1, 96, 45, 91, 66, 94, 87, 22],
       [57, 22, 10,  2, 40, 85, 94,  1,  8,  5]])

In [181]:
a>80

array([[ True, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False,  True, False,  True, False,  True,  True,
        False],
       [False, False, False, False, False,  True,  True, False, False,
        False]])

In [183]:
a %2 ==0

array([[False, False, False,  True,  True,  True, False,  True, False,
         True],
       [ True,  True, False,  True,  True,  True, False, False,  True,
         True],
       [ True,  True,  True,  True, False,  True,  True, False,  True,
        False],
       [ True, False, False,  True, False, False,  True,  True, False,
         True],
       [False,  True,  True,  True,  True, False,  True, False,  True,
        False]])

In [185]:
a[a %2 !=0]

array([87, 67, 39, 73,  7, 35,  5, 13, 83, 19, 53, 57,  1, 45, 91, 87, 57,
       85,  1,  5])

In [192]:
a[a > 80]

array([87, 84, 96, 83, 96, 91, 94, 87, 85, 94])

In [191]:
# boolean indexing
a[~(a > 80) & ~(a %2 !=0)]

array([34, 70, 36, 60, 58, 76, 80, 62, 80, 20, 74, 62,  6, 70, 40, 26, 50,
       16, 66, 22, 22, 10,  2, 40,  8])

In [ ]:
# & ==> for adding multiple conditons
# ~ ==> represents !=

In [ ]:

a[(a > 20) & (a % 2 != 0)]

In [ ]:
a[~(a%4 ==0)]

In [193]:
# null
a = np.array([1,2,3,np.nan])

In [194]:
a

array([ 1.,  2.,  3., nan])